优化启动参数，优化停止方式

diff --git a/springboot-starter b/springboot-starter
--- a/springboot-starter
+++ b/springboot-starter
@@ -10,7 +10,7 @@
 ## 获取 java 命令的路径
 JAVA_CMD=`which java`
 
-if [ -z "$JAVA_CMD" ];then
+if [ -z "${JAVA_CMD}" ];then
   echo "Please install the Java environment";
   exit 1;
 fi
@@ -33,20 +33,25 @@ APP_NAME=$1;
 ## 操作
 OPERATION=$2;
 
-## jvm 参数
-XMS=$3
-XMX=$4
+## 运行模式
+MODEL=$3
 
-if [ -z "$XMS" ]; then
-    XMS="-Xms256m"
-  else
-    XMS="-Xms${XMS}m"
+if [ -z "$MODEL" ]; then
+    MODEL="production"
 fi
-if [ -z "$XMX" ]; then
-    XMX="-Xms512m"
-  else
-    XMX="-Xms${XMX}m"
+
+## 其它参数处理
+OTHER_ARGS=""
+if [ $# -gt 3 ]; then
+    shift 3
+else
+    shift $#
 fi
+for ARG in $*
+do
+  OTHER_ARGS="$OTHER_ARGS $ARG"
+done
+
 
 ## 脚本所在目录，绝对路径表示
 BASE_PATH=$(cd `dirname $APP_NAME`;pwd)
@@ -61,8 +66,8 @@ APP_PATH=$BASE_PATH"/"$APP_NAME
 ## 判断目标程序是否已经启动
 is_running(){
   ## 尝试获取已经运行程序的PID
-  PID=`ps -ef|grep $APP_PATH|grep -v grep|awk '{print $2}'`
-  if [ -z "$PID" ]; then
+  PID=`ps -ef|grep ${APP_PATH}|grep -v grep|awk '{print $2}'`
+  if [ -z "${PID}" ]; then
     return 0
   else
     return 1
@@ -77,9 +82,11 @@ start(){
   else
     ## 启动 jar 包
     echo "${APP_NAME} starting ...... "
-    nohup $JAVA_CMD -jar ${XMS} ${XMX} -Dspring.profiles.active=production ${APP_PATH} > /dev/null 2>&1 &
+    nohup ${JAVA_CMD} -jar ${OTHER_ARGS} -Dspring.profiles.active=${MODEL} ${APP_PATH} > /dev/null 2>&1 &
+    echo "nohup ${JAVA_CMD} -jar ${OTHER_ARGS} -Dspring.profiles.active=${MODEL} ${APP_PATH} > /dev/null 2>&1 &"
     sleep 1
     echo "${APP_NAME} started  completed "
+    echo ""
   fi
 }
 
@@ -87,8 +94,12 @@ start(){
 stop(){
   is_running
   if [ $? -eq "1" ]; then
-    echo "PID is $PID, ${APP_NAME}  stopping ...... "
-    kill -9 $PID
+    echo "PID is ${PID}, ${APP_NAME} stopping ...... "
+    kill ${PID}
+    if [ $? -ne "0" ]; then
+        echo "kill ${PID} failed，execute kill -9 ${PID}"
+        kill -9 ${PID}
+    fi
     sleep 1
     echo "${APP_NAME} stopped completed "
   else
@@ -126,5 +137,3 @@ case "$OPERATION" in
     usage ;;
 esac
 exit 0
-
-
